apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: skupper-operator
  namespace: olm
spec:
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/fgiorgetti/skupper-operator-index:v1.5.3-rc
  sourceType: grpc
