apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: skupper-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/skupper/skupper-operator-index:v1.2.1
  grpcPodConfig:
    securityContextConfig: restricted
